apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "react-onechart.fullname" . }}
  labels:
    {{- include "react-onechart.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml .Values.config | nindent 4 }}
